[package]
name = "okx_example"
type = "contract"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-nr", tag="v4.0.0-devnet.2-patch.1", directory="aztec" }
att_verifier_lib = { path = "../../att_verifier_lib" }